heidi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'heidi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('portfolio.urls')),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import patterns, include, url
#from django.conf.urls.static import static
#from django.conf import settings

from portfolio import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/models.py
from django.db import models
from imagekit.processors import ResizeToFill
from imagekit.models import ImageSpecField

# Create your models here.
class Block(models.Model):
    block_id = models.CharField(max_length=200)
    content = models.TextField()

    def __unicode__(self):
        return self.block_id


class Tag(models.Model):
    tag = models.CharField(max_length=200)

    def __unicode__(self):
        return self.tag


class Artwork(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    date_created = models.DateField(null=True, blank=True)
    artwork_tags = models.ManyToManyField(Tag)
    show_title = models.BooleanField()
    sort_order = models.IntegerField()

    image = models.FileField(upload_to="artwork")
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(500, 500)], format='JPEG',
                                 options={'quality': 99})

    def __unicode__(self):
        return self.title

portfolio/forms.py
from django import forms
from captcha.fields import ReCaptchaField

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, initial='Ditt namn')
    sender = forms.EmailField(initial='din@epostadress.se')
    validation = forms.CharField(max_length=100, initial='Antispam: Fyll i mitt efternamn')
    message = forms.CharField(widget=forms.Textarea, initial='Meddelande')

portfolio/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from portfolio.models import Block, Artwork, Tag
from portfolio.forms import ContactForm
from django.core.mail import send_mail

def index(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            validation = request.POST['validation'].strip().lower()
            if validation == 'nesset' or validation == 'heidi nesset' or validation == 'heidi' or validation == 'heidinesset':
                message = u'Ämne: ' + request.POST['subject'] + "\n" \
                    u'Avsändare: ' + request.POST['sender'] + "\n\n" \
                    'Meddelande:' + "\n" + request.POST['message']

                send_mail(u'Kontaktförfrågan från heidinesset.com', message, 'web@heidinesset.com',
                    ['heidi@heidinesset.com'], fail_silently=False)


    try:
        contact_block = Block.objects.get(block_id='contact')
    except:
        contact_block = None

    try:
        about_block = Block.objects.get(block_id='about')
    except:
        about_block = None

    try:
        footer_block = Block.objects.get(block_id='footer')
    except:
        footer_block = None

    artworks = Artwork.objects.all().order_by('-sort_order')
    contact_form = ContactForm()
    tags = Tag.objects.all()
    context = {
        'contact_block': contact_block,
        'contact_form': contact_form,
        'footer_block': footer_block,
        'about_block': about_block,
        'artwork_list': artworks,
        'tag_list': tags
    }
    return render(request, 'index.html', context)

portfolio/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Heidi Nesset - Illustration &amp; form</title>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
        <link rel="stylesheet" type="text/css" href="{% static "heidi/stylesheets/screen.css" %}"/>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-37596066-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        {% block content %}{% endblock %}

        <script type="text/javascript" src="{% static "js/jquery-1.11.0.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/magnific-popup.min.js" %}"></script>
        <script type="text/javascript" src="{% static "js/main.js" %}"></script>
        <link href='http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Fenix' rel='stylesheet' type='text/css'>
    </body>
</html>

<!-- hemlig kod: #e98457 -->

portfolio/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load markdown_deux_tags %}

{% block content %}
<div class="container main">
    <header class="header">
        <div class="top">
            <nav class="topmenu">
                <ul>
                    <li>
                        <a class="open-popup-link" href="#contact">Kontakt</a>
                    </li>
                    <li>
                        <a class="open-popup-link" href="#about">Om mig</a>
                    </li>
                </ul>
            </nav>
            <div class="logo">
                <img id="logo-img" src="{% static 'images/logotyp_heidinesset.png' %}" alt="Heidi Nesset">
            </div>
            <div class="social-links">
                <a href="http://instagram.com/heidinesset" class="instagram"><img src="{% static 'images/social/instagram.png' %}"></a>
                <a href="https://www.facebook.com/illusbyheidi" class="facebook"><img src="{% static 'images/social/facebook.png' %}"></a>
                <a href="http://www.pinterest.com/heyaya/" class="pinterest"><img src="{% static 'images/social/pinterest.png' %}"></a>
                <a href="http://se.linkedin.com/pub/heidi-nesset/57/874/3b1" class="linkedin"><img src="{% static 'images/social/linkedin.png' %}"></a>
            </div>
        </div>
    </header>
</div>

<div class="separator">&nbsp;</div>

<div class="about white-popup mfp-hide" id="about">
    {{ about_block.content|markdown }}
</div>
<div class="contact white-popup mfp-hide" id="contact">
    {% if contact_block and contact_block.content and contact_block.content.strip %}
    <div class="textblock">
        {{ contact_block.content|markdown }}
    </div>
    {% endif %}
    <form action="" method="post">{% csrf_token %}
        <div class="left">
            <input id="id_subject" maxlength="100" name="subject" type="text" value="Ditt namn">
            <input id="id_sender" name="sender" type="email" value="din@epostadress.se">
            <input id="id_validation" maxlength="100" name="validation" type="text" value="Antispam: Fyll i mitt efternamn">
        </div>
        <div class="right">
            <textarea cols="40" id="id_message" name="message" rows="10">Meddelande</textarea>
        </div>
        <div class="buttons">
            <input type="submit" value="Skicka">
        </div>
    </form>
</div>

<div class="container">
    <div class="work" id="work">
        <!--
        <div class="filters">
            <ul>
                <li>Humour</li>
                <li>Satire</li>
                <li>Paintings</li>
            </ul>
        </div>
        -->
        <div class="listing">
        {% for artwork in artwork_list %}
            <div class="item">
                <a class="open-image-popup" href="{{ artwork.image.url }}">
                    <img src="{{ artwork.image_thumbnail.url }}">
                </a>
                {% if artwork.title and artwork.title.strip and artwork.show_title %}
                    <div class="background">&nbsp;</div>
                    <h4>{{ artwork.title.strip }}</h4>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div>
</div>

<div class="separator">&nbsp;</div>

{% if footer_block %}
<div class="container">
    <footer class="bottom">
        {{ footer_block.content|markdown }}
    </footer>
</div>
{% endif %}

{% endblock %}